//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOR.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SICOR_DBEntities : DbContext
    {
        public SICOR_DBEntities()
            : base("name=SICOR_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_cat_categoriaGT_Result> sp_cat_categoriaGT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cat_categoriaGT_Result>("sp_cat_categoriaGT");
        }
    
        public virtual ObjectResult<sp_cat_claseGT_Result> sp_cat_claseGT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cat_claseGT_Result>("sp_cat_claseGT");
        }
    
        public virtual ObjectResult<sp_cat_estadoGT_Result> sp_cat_estadoGT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cat_estadoGT_Result>("sp_cat_estadoGT");
        }
    
        public virtual ObjectResult<sp_cat_tipoGT_Result> sp_cat_tipoGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cat_tipoGT_Result>("sp_cat_tipoGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_remitidoGT_Result> sp_remitidoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_remitidoGT_Result>("sp_remitidoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_remitidoSV_Result> sp_remitidoSV(Nullable<int> rEMID, Nullable<int> cLM_USRS_ID, Nullable<int> cORRESID, Nullable<System.DateTime> rEMFEC, Nullable<int> uPDATEUSRID)
        {
            var rEMIDParameter = rEMID.HasValue ?
                new ObjectParameter("REMID", rEMID) :
                new ObjectParameter("REMID", typeof(int));
    
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var rEMFECParameter = rEMFEC.HasValue ?
                new ObjectParameter("REMFEC", rEMFEC) :
                new ObjectParameter("REMFEC", typeof(System.DateTime));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_remitidoSV_Result>("sp_remitidoSV", rEMIDParameter, cLM_USRS_IDParameter, cORRESIDParameter, rEMFECParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_estadoGT_Result> sp_estadoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_estadoGT_Result>("sp_estadoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_estadoSV_Result> sp_estadoSV(Nullable<int> eSTCORRID, Nullable<int> cORRESID, Nullable<int> eSTADOID, Nullable<byte> eSTADOACTIVO, Nullable<int> uPDATEUSRID)
        {
            var eSTCORRIDParameter = eSTCORRID.HasValue ?
                new ObjectParameter("ESTCORRID", eSTCORRID) :
                new ObjectParameter("ESTCORRID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var eSTADOIDParameter = eSTADOID.HasValue ?
                new ObjectParameter("ESTADOID", eSTADOID) :
                new ObjectParameter("ESTADOID", typeof(int));
    
            var eSTADOACTIVOParameter = eSTADOACTIVO.HasValue ?
                new ObjectParameter("ESTADOACTIVO", eSTADOACTIVO) :
                new ObjectParameter("ESTADOACTIVO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_estadoSV_Result>("sp_estadoSV", eSTCORRIDParameter, cORRESIDParameter, eSTADOIDParameter, eSTADOACTIVOParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_usuariosGT_Result> sp_usuariosGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_usuariosGT_Result>("sp_usuariosGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_usuariosVerifGT_Result> sp_usuariosVerifGT(string uSRS_NMB, string uSRS_PASS)
        {
            var uSRS_NMBParameter = uSRS_NMB != null ?
                new ObjectParameter("USRS_NMB", uSRS_NMB) :
                new ObjectParameter("USRS_NMB", typeof(string));
    
            var uSRS_PASSParameter = uSRS_PASS != null ?
                new ObjectParameter("USRS_PASS", uSRS_PASS) :
                new ObjectParameter("USRS_PASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_usuariosVerifGT_Result>("sp_usuariosVerifGT", uSRS_NMBParameter, uSRS_PASSParameter);
        }
    
        public virtual ObjectResult<sp_margiPendienteUpdate_Result> sp_margiPendienteUpdate(Nullable<int> mARGID, Nullable<byte> mARGPENDIENTE, Nullable<int> uPDATEUSRID)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            var mARGPENDIENTEParameter = mARGPENDIENTE.HasValue ?
                new ObjectParameter("MARGPENDIENTE", mARGPENDIENTE) :
                new ObjectParameter("MARGPENDIENTE", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiPendienteUpdate_Result>("sp_margiPendienteUpdate", mARGIDParameter, mARGPENDIENTEParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_archivoGT_Result> sp_archivoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_archivoGT_Result>("sp_archivoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_archivoSV_Result> sp_archivoSV(Nullable<int> aRCHID, Nullable<int> cORRESID, Nullable<int> aRCHIVO, string aRCHVOCOD, string aRCHVODSC, Nullable<int> tIPOID, Nullable<int> uPDATEUSRID, Nullable<int> grupo)
        {
            var aRCHIDParameter = aRCHID.HasValue ?
                new ObjectParameter("ARCHID", aRCHID) :
                new ObjectParameter("ARCHID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var aRCHIVOParameter = aRCHIVO.HasValue ?
                new ObjectParameter("ARCHIVO", aRCHIVO) :
                new ObjectParameter("ARCHIVO", typeof(int));
    
            var aRCHVOCODParameter = aRCHVOCOD != null ?
                new ObjectParameter("ARCHVOCOD", aRCHVOCOD) :
                new ObjectParameter("ARCHVOCOD", typeof(string));
    
            var aRCHVODSCParameter = aRCHVODSC != null ?
                new ObjectParameter("ARCHVODSC", aRCHVODSC) :
                new ObjectParameter("ARCHVODSC", typeof(string));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_archivoSV_Result>("sp_archivoSV", aRCHIDParameter, cORRESIDParameter, aRCHIVOParameter, aRCHVOCODParameter, aRCHVODSCParameter, tIPOIDParameter, uPDATEUSRIDParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_adjuntoGT_Result> sp_adjuntoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_adjuntoGT_Result>("sp_adjuntoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_adjuntoSV_Result> sp_adjuntoSV(Nullable<int> aDJUNTOID, Nullable<int> cORRESID, string aDJUNTO_NAME, string aDJUNTO_SIZE, string aDJUNTO_TYPE, string aDJUNTO_URLDOWN, string aDJUNTO_URLDEL, Nullable<byte> aDJUNTO_TIPO, Nullable<int> uPDATEUSRID, Nullable<int> grupo)
        {
            var aDJUNTOIDParameter = aDJUNTOID.HasValue ?
                new ObjectParameter("ADJUNTOID", aDJUNTOID) :
                new ObjectParameter("ADJUNTOID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var aDJUNTO_NAMEParameter = aDJUNTO_NAME != null ?
                new ObjectParameter("ADJUNTO_NAME", aDJUNTO_NAME) :
                new ObjectParameter("ADJUNTO_NAME", typeof(string));
    
            var aDJUNTO_SIZEParameter = aDJUNTO_SIZE != null ?
                new ObjectParameter("ADJUNTO_SIZE", aDJUNTO_SIZE) :
                new ObjectParameter("ADJUNTO_SIZE", typeof(string));
    
            var aDJUNTO_TYPEParameter = aDJUNTO_TYPE != null ?
                new ObjectParameter("ADJUNTO_TYPE", aDJUNTO_TYPE) :
                new ObjectParameter("ADJUNTO_TYPE", typeof(string));
    
            var aDJUNTO_URLDOWNParameter = aDJUNTO_URLDOWN != null ?
                new ObjectParameter("ADJUNTO_URLDOWN", aDJUNTO_URLDOWN) :
                new ObjectParameter("ADJUNTO_URLDOWN", typeof(string));
    
            var aDJUNTO_URLDELParameter = aDJUNTO_URLDEL != null ?
                new ObjectParameter("ADJUNTO_URLDEL", aDJUNTO_URLDEL) :
                new ObjectParameter("ADJUNTO_URLDEL", typeof(string));
    
            var aDJUNTO_TIPOParameter = aDJUNTO_TIPO.HasValue ?
                new ObjectParameter("ADJUNTO_TIPO", aDJUNTO_TIPO) :
                new ObjectParameter("ADJUNTO_TIPO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_adjuntoSV_Result>("sp_adjuntoSV", aDJUNTOIDParameter, cORRESIDParameter, aDJUNTO_NAMEParameter, aDJUNTO_SIZEParameter, aDJUNTO_TYPEParameter, aDJUNTO_URLDOWNParameter, aDJUNTO_URLDELParameter, aDJUNTO_TIPOParameter, uPDATEUSRIDParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_mensaje_inGT_Result> sp_mensaje_inGT(Nullable<int> cLM_USRS_ID)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensaje_inGT_Result>("sp_mensaje_inGT", cLM_USRS_IDParameter);
        }
    
        public virtual ObjectResult<sp_mensaje_inSV_Result> sp_mensaje_inSV(Nullable<int> mSJINID, Nullable<int> cORRESID, Nullable<int> cLM_USRS_ID, Nullable<int> tIPOID, string mSJINMENSAJE, Nullable<int> uPDATEUSRID)
        {
            var mSJINIDParameter = mSJINID.HasValue ?
                new ObjectParameter("MSJINID", mSJINID) :
                new ObjectParameter("MSJINID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var mSJINMENSAJEParameter = mSJINMENSAJE != null ?
                new ObjectParameter("MSJINMENSAJE", mSJINMENSAJE) :
                new ObjectParameter("MSJINMENSAJE", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensaje_inSV_Result>("sp_mensaje_inSV", mSJINIDParameter, cORRESIDParameter, cLM_USRS_IDParameter, tIPOIDParameter, mSJINMENSAJEParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_mensajeEnvi_inGT_Result> sp_mensajeEnvi_inGT(Nullable<int> cLM_USRS_ID)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensajeEnvi_inGT_Result>("sp_mensajeEnvi_inGT", cLM_USRS_IDParameter);
        }
    
        public virtual ObjectResult<sp_mensajeRecib_inGT_Result> sp_mensajeRecib_inGT(Nullable<int> cLM_USRS_ID)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensajeRecib_inGT_Result>("sp_mensajeRecib_inGT", cLM_USRS_IDParameter);
        }
    
        public virtual ObjectResult<sp_mensajeRecibNum_inGT_Result> sp_mensajeRecibNum_inGT(Nullable<int> cLM_USRS_ID)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensajeRecibNum_inGT_Result>("sp_mensajeRecibNum_inGT", cLM_USRS_IDParameter);
        }
    
        public virtual ObjectResult<sp_mensajeUpLeido_inGT_Result> sp_mensajeUpLeido_inGT(Nullable<int> cLM_USRS_ID)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensajeUpLeido_inGT_Result>("sp_mensajeUpLeido_inGT", cLM_USRS_IDParameter);
        }
    
        public virtual ObjectResult<sp_mensajeByIdFech_inGT_Result> sp_mensajeByIdFech_inGT(Nullable<int> cLM_USRS_ID, Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02)
        {
            var cLM_USRS_IDParameter = cLM_USRS_ID.HasValue ?
                new ObjectParameter("CLM_USRS_ID", cLM_USRS_ID) :
                new ObjectParameter("CLM_USRS_ID", typeof(int));
    
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensajeByIdFech_inGT_Result>("sp_mensajeByIdFech_inGT", cLM_USRS_IDParameter, fECH01Parameter, fECH02Parameter);
        }
    
        public virtual ObjectResult<sp_mensaje_exSV_Result> sp_mensaje_exSV(Nullable<int> mSJEXID, Nullable<int> cORRESID, Nullable<int> cONTID, Nullable<int> tIPOID, string mSJEXMENSAJE, Nullable<int> uPDATEUSRID)
        {
            var mSJEXIDParameter = mSJEXID.HasValue ?
                new ObjectParameter("MSJEXID", mSJEXID) :
                new ObjectParameter("MSJEXID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var mSJEXMENSAJEParameter = mSJEXMENSAJE != null ?
                new ObjectParameter("MSJEXMENSAJE", mSJEXMENSAJE) :
                new ObjectParameter("MSJEXMENSAJE", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mensaje_exSV_Result>("sp_mensaje_exSV", mSJEXIDParameter, cORRESIDParameter, cONTIDParameter, tIPOIDParameter, mSJEXMENSAJEParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_remiConfirByUsridGT_Result> sp_remiConfirByUsridGT(Nullable<int> uSRID)
        {
            var uSRIDParameter = uSRID.HasValue ?
                new ObjectParameter("USRID", uSRID) :
                new ObjectParameter("USRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_remiConfirByUsridGT_Result>("sp_remiConfirByUsridGT", uSRIDParameter);
        }
    
        public virtual ObjectResult<sp_remiConfirSV_Result> sp_remiConfirSV(Nullable<int> rEMID)
        {
            var rEMIDParameter = rEMID.HasValue ?
                new ObjectParameter("REMID", rEMID) :
                new ObjectParameter("REMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_remiConfirSV_Result>("sp_remiConfirSV", rEMIDParameter);
        }
    
        public virtual ObjectResult<sp_usuariosUpPassSV_Result> sp_usuariosUpPassSV(Nullable<int> iD, string pSS, string nPSS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pSSParameter = pSS != null ?
                new ObjectParameter("PSS", pSS) :
                new ObjectParameter("PSS", typeof(string));
    
            var nPSSParameter = nPSS != null ?
                new ObjectParameter("NPSS", nPSS) :
                new ObjectParameter("NPSS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_usuariosUpPassSV_Result>("sp_usuariosUpPassSV", iDParameter, pSSParameter, nPSSParameter);
        }
    
        public virtual ObjectResult<sp_contactosByInstGT_Result> sp_contactosByInstGT(string cONTINST)
        {
            var cONTINSTParameter = cONTINST != null ?
                new ObjectParameter("CONTINST", cONTINST) :
                new ObjectParameter("CONTINST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactosByInstGT_Result>("sp_contactosByInstGT", cONTINSTParameter);
        }
    
        public virtual ObjectResult<sp_contactosGT_Result> sp_contactosGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactosGT_Result>("sp_contactosGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_contactosInternosGT_Result> sp_contactosInternosGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactosInternosGT_Result>("sp_contactosInternosGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_contactosSV_Result> sp_contactosSV(Nullable<int> cONTID, string cONTNOMBRE, string cONTCARGO, string cONTINST, string cONTUNIDAD, string cONTDSC, Nullable<int> tIPOID, string cONTEMAIL, string cONTTELS, Nullable<int> uPDATEUSRID, Nullable<int> gRUPO)
        {
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var cONTNOMBREParameter = cONTNOMBRE != null ?
                new ObjectParameter("CONTNOMBRE", cONTNOMBRE) :
                new ObjectParameter("CONTNOMBRE", typeof(string));
    
            var cONTCARGOParameter = cONTCARGO != null ?
                new ObjectParameter("CONTCARGO", cONTCARGO) :
                new ObjectParameter("CONTCARGO", typeof(string));
    
            var cONTINSTParameter = cONTINST != null ?
                new ObjectParameter("CONTINST", cONTINST) :
                new ObjectParameter("CONTINST", typeof(string));
    
            var cONTUNIDADParameter = cONTUNIDAD != null ?
                new ObjectParameter("CONTUNIDAD", cONTUNIDAD) :
                new ObjectParameter("CONTUNIDAD", typeof(string));
    
            var cONTDSCParameter = cONTDSC != null ?
                new ObjectParameter("CONTDSC", cONTDSC) :
                new ObjectParameter("CONTDSC", typeof(string));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var cONTEMAILParameter = cONTEMAIL != null ?
                new ObjectParameter("CONTEMAIL", cONTEMAIL) :
                new ObjectParameter("CONTEMAIL", typeof(string));
    
            var cONTTELSParameter = cONTTELS != null ?
                new ObjectParameter("CONTTELS", cONTTELS) :
                new ObjectParameter("CONTTELS", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            var gRUPOParameter = gRUPO.HasValue ?
                new ObjectParameter("GRUPO", gRUPO) :
                new ObjectParameter("GRUPO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactosSV_Result>("sp_contactosSV", cONTIDParameter, cONTNOMBREParameter, cONTCARGOParameter, cONTINSTParameter, cONTUNIDADParameter, cONTDSCParameter, tIPOIDParameter, cONTEMAILParameter, cONTTELSParameter, uPDATEUSRIDParameter, gRUPOParameter);
        }
    
        public virtual ObjectResult<sp_contInstGT_Result> sp_contInstGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contInstGT_Result>("sp_contInstGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_contUnidadGT_Result> sp_contUnidadGT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contUnidadGT_Result>("sp_contUnidadGT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullSV_Result> sp_detallefullSV(Nullable<int> cORRESID, string cORRESCOD, Nullable<int> cLASEID, Nullable<int> tIPOID, Nullable<int> pRIOID, Nullable<int> cONTID_REMITE, Nullable<int> cATEGOID, string aSUNTO, Nullable<System.DateTime> nOTAELABFEC, Nullable<System.DateTime> nOTARECIBFEC, Nullable<System.TimeSpan> nOTARECIBHORA, Nullable<byte> rEQFIRMA, string aDJUNTO, Nullable<int> cONTID_DIRIGIDO, Nullable<int> cONTID_ELABORO, Nullable<int> cORRESID_CONTESTA, Nullable<int> mARGINAID, string mARGINAFORMARES, Nullable<byte> eLIMINADO, Nullable<int> uPDATEUSRID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cORRESCODParameter = cORRESCOD != null ?
                new ObjectParameter("CORRESCOD", cORRESCOD) :
                new ObjectParameter("CORRESCOD", typeof(string));
    
            var cLASEIDParameter = cLASEID.HasValue ?
                new ObjectParameter("CLASEID", cLASEID) :
                new ObjectParameter("CLASEID", typeof(int));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var pRIOIDParameter = pRIOID.HasValue ?
                new ObjectParameter("PRIOID", pRIOID) :
                new ObjectParameter("PRIOID", typeof(int));
    
            var cONTID_REMITEParameter = cONTID_REMITE.HasValue ?
                new ObjectParameter("CONTID_REMITE", cONTID_REMITE) :
                new ObjectParameter("CONTID_REMITE", typeof(int));
    
            var cATEGOIDParameter = cATEGOID.HasValue ?
                new ObjectParameter("CATEGOID", cATEGOID) :
                new ObjectParameter("CATEGOID", typeof(int));
    
            var aSUNTOParameter = aSUNTO != null ?
                new ObjectParameter("ASUNTO", aSUNTO) :
                new ObjectParameter("ASUNTO", typeof(string));
    
            var nOTAELABFECParameter = nOTAELABFEC.HasValue ?
                new ObjectParameter("NOTAELABFEC", nOTAELABFEC) :
                new ObjectParameter("NOTAELABFEC", typeof(System.DateTime));
    
            var nOTARECIBFECParameter = nOTARECIBFEC.HasValue ?
                new ObjectParameter("NOTARECIBFEC", nOTARECIBFEC) :
                new ObjectParameter("NOTARECIBFEC", typeof(System.DateTime));
    
            var nOTARECIBHORAParameter = nOTARECIBHORA.HasValue ?
                new ObjectParameter("NOTARECIBHORA", nOTARECIBHORA) :
                new ObjectParameter("NOTARECIBHORA", typeof(System.TimeSpan));
    
            var rEQFIRMAParameter = rEQFIRMA.HasValue ?
                new ObjectParameter("REQFIRMA", rEQFIRMA) :
                new ObjectParameter("REQFIRMA", typeof(byte));
    
            var aDJUNTOParameter = aDJUNTO != null ?
                new ObjectParameter("ADJUNTO", aDJUNTO) :
                new ObjectParameter("ADJUNTO", typeof(string));
    
            var cONTID_DIRIGIDOParameter = cONTID_DIRIGIDO.HasValue ?
                new ObjectParameter("CONTID_DIRIGIDO", cONTID_DIRIGIDO) :
                new ObjectParameter("CONTID_DIRIGIDO", typeof(int));
    
            var cONTID_ELABOROParameter = cONTID_ELABORO.HasValue ?
                new ObjectParameter("CONTID_ELABORO", cONTID_ELABORO) :
                new ObjectParameter("CONTID_ELABORO", typeof(int));
    
            var cORRESID_CONTESTAParameter = cORRESID_CONTESTA.HasValue ?
                new ObjectParameter("CORRESID_CONTESTA", cORRESID_CONTESTA) :
                new ObjectParameter("CORRESID_CONTESTA", typeof(int));
    
            var mARGINAIDParameter = mARGINAID.HasValue ?
                new ObjectParameter("MARGINAID", mARGINAID) :
                new ObjectParameter("MARGINAID", typeof(int));
    
            var mARGINAFORMARESParameter = mARGINAFORMARES != null ?
                new ObjectParameter("MARGINAFORMARES", mARGINAFORMARES) :
                new ObjectParameter("MARGINAFORMARES", typeof(string));
    
            var eLIMINADOParameter = eLIMINADO.HasValue ?
                new ObjectParameter("ELIMINADO", eLIMINADO) :
                new ObjectParameter("ELIMINADO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullSV_Result>("sp_detallefullSV", cORRESIDParameter, cORRESCODParameter, cLASEIDParameter, tIPOIDParameter, pRIOIDParameter, cONTID_REMITEParameter, cATEGOIDParameter, aSUNTOParameter, nOTAELABFECParameter, nOTARECIBFECParameter, nOTARECIBHORAParameter, rEQFIRMAParameter, aDJUNTOParameter, cONTID_DIRIGIDOParameter, cONTID_ELABOROParameter, cORRESID_CONTESTAParameter, mARGINAIDParameter, mARGINAFORMARESParameter, eLIMINADOParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_detallefullGT_Result2> sp_detallefullGT(Nullable<int> tipo, Nullable<int> grupo)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullGT_Result2>("sp_detallefullGT", tipoParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByIdGT_Result> sp_detallefullByIdGT(Nullable<int> cORRESID, Nullable<int> grupo)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByIdGT_Result>("sp_detallefullByIdGT", cORRESIDParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByFechaGT_Result> sp_detallefullByFechaGT(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> grupo)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByFechaGT_Result>("sp_detallefullByFechaGT", fECH01Parameter, fECH02Parameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByContNombrePadreGT_Result> sp_detallefullByContNombrePadreGT(string cONT)
        {
            var cONTParameter = cONT != null ?
                new ObjectParameter("CONT", cONT) :
                new ObjectParameter("CONT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByContNombrePadreGT_Result>("sp_detallefullByContNombrePadreGT", cONTParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByContIdPadreGT_Result> sp_detallefullByContIdPadreGT(Nullable<int> cONTID, Nullable<int> grupo)
        {
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByContIdPadreGT_Result>("sp_detallefullByContIdPadreGT", cONTIDParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByContestaIdGT_Result> sp_detallefullByContestaIdGT(Nullable<int> cORRESID_CONTESTA, Nullable<int> grupo)
        {
            var cORRESID_CONTESTAParameter = cORRESID_CONTESTA.HasValue ?
                new ObjectParameter("CORRESID_CONTESTA", cORRESID_CONTESTA) :
                new ObjectParameter("CORRESID_CONTESTA", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByContestaIdGT_Result>("sp_detallefullByContestaIdGT", cORRESID_CONTESTAParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByCodGT_Result> sp_detallefullByCodGT(string cORRESCOD, Nullable<int> grupo)
        {
            var cORRESCODParameter = cORRESCOD != null ?
                new ObjectParameter("CORRESCOD", cORRESCOD) :
                new ObjectParameter("CORRESCOD", typeof(string));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByCodGT_Result>("sp_detallefullByCodGT", cORRESCODParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByAsuntoGT_Result> sp_detallefullByAsuntoGT(string aSUNTO, Nullable<int> grupo)
        {
            var aSUNTOParameter = aSUNTO != null ?
                new ObjectParameter("ASUNTO", aSUNTO) :
                new ObjectParameter("ASUNTO", typeof(string));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByAsuntoGT_Result>("sp_detallefullByAsuntoGT", aSUNTOParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_corresFimaSV_Result> sp_corresFimaSV(Nullable<int> cORRESID, Nullable<byte> rEQFIRMA, Nullable<int> uPDATEUSRID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var rEQFIRMAParameter = rEQFIRMA.HasValue ?
                new ObjectParameter("REQFIRMA", rEQFIRMA) :
                new ObjectParameter("REQFIRMA", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresFimaSV_Result>("sp_corresFimaSV", cORRESIDParameter, rEQFIRMAParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_corresElimSV_Result> sp_corresElimSV(Nullable<int> cORRESID, Nullable<int> mARGINAID, Nullable<byte> eLIMINADO, Nullable<int> uPDATEUSRID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var mARGINAIDParameter = mARGINAID.HasValue ?
                new ObjectParameter("MARGINAID", mARGINAID) :
                new ObjectParameter("MARGINAID", typeof(int));
    
            var eLIMINADOParameter = eLIMINADO.HasValue ?
                new ObjectParameter("ELIMINADO", eLIMINADO) :
                new ObjectParameter("ELIMINADO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresElimSV_Result>("sp_corresElimSV", cORRESIDParameter, mARGINAIDParameter, eLIMINADOParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_corresDebUpSV_Result> sp_corresDebUpSV(Nullable<int> cORRESDEBID, Nullable<int> cORRESID, Nullable<System.DateTime> cORRESDEB_RECIBFEC, string cORRESDEB_RECIBHORA, Nullable<int> uPDATEUSRID)
        {
            var cORRESDEBIDParameter = cORRESDEBID.HasValue ?
                new ObjectParameter("CORRESDEBID", cORRESDEBID) :
                new ObjectParameter("CORRESDEBID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cORRESDEB_RECIBFECParameter = cORRESDEB_RECIBFEC.HasValue ?
                new ObjectParameter("CORRESDEB_RECIBFEC", cORRESDEB_RECIBFEC) :
                new ObjectParameter("CORRESDEB_RECIBFEC", typeof(System.DateTime));
    
            var cORRESDEB_RECIBHORAParameter = cORRESDEB_RECIBHORA != null ?
                new ObjectParameter("CORRESDEB_RECIBHORA", cORRESDEB_RECIBHORA) :
                new ObjectParameter("CORRESDEB_RECIBHORA", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresDebUpSV_Result>("sp_corresDebUpSV", cORRESDEBIDParameter, cORRESIDParameter, cORRESDEB_RECIBFECParameter, cORRESDEB_RECIBHORAParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_corresDebSV_Result> sp_corresDebSV(Nullable<int> cORRESDEBID, Nullable<int> cORRESID, string cORRESDEBDSC, Nullable<System.DateTime> cORRESDEBFEC, Nullable<int> uPDATEUSRID)
        {
            var cORRESDEBIDParameter = cORRESDEBID.HasValue ?
                new ObjectParameter("CORRESDEBID", cORRESDEBID) :
                new ObjectParameter("CORRESDEBID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cORRESDEBDSCParameter = cORRESDEBDSC != null ?
                new ObjectParameter("CORRESDEBDSC", cORRESDEBDSC) :
                new ObjectParameter("CORRESDEBDSC", typeof(string));
    
            var cORRESDEBFECParameter = cORRESDEBFEC.HasValue ?
                new ObjectParameter("CORRESDEBFEC", cORRESDEBFEC) :
                new ObjectParameter("CORRESDEBFEC", typeof(System.DateTime));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresDebSV_Result>("sp_corresDebSV", cORRESDEBIDParameter, cORRESIDParameter, cORRESDEBDSCParameter, cORRESDEBFECParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_corresDebByCorresIdGT_Result> sp_corresDebByCorresIdGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresDebByCorresIdGT_Result>("sp_corresDebByCorresIdGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_corresActivoSV_Result> sp_corresActivoSV(Nullable<int> cORRESID, Nullable<byte> aCTIVO, Nullable<int> uPDATEUSRID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var aCTIVOParameter = aCTIVO.HasValue ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresActivoSV_Result>("sp_corresActivoSV", cORRESIDParameter, aCTIVOParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_margiContSV_Result> sp_margiContSV(Nullable<int> mARGICONTID, Nullable<int> mARGID, Nullable<int> cONTID, Nullable<int> tIPOID, Nullable<System.DateTime> mARGRECIBFEC, string mARGRECIBHORA, string mARGRECIBNOMBRE, Nullable<byte> eNVIOFISICO, Nullable<byte> eNVIODIGITAL, Nullable<int> uPDATEUSRID)
        {
            var mARGICONTIDParameter = mARGICONTID.HasValue ?
                new ObjectParameter("MARGICONTID", mARGICONTID) :
                new ObjectParameter("MARGICONTID", typeof(int));
    
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var mARGRECIBFECParameter = mARGRECIBFEC.HasValue ?
                new ObjectParameter("MARGRECIBFEC", mARGRECIBFEC) :
                new ObjectParameter("MARGRECIBFEC", typeof(System.DateTime));
    
            var mARGRECIBHORAParameter = mARGRECIBHORA != null ?
                new ObjectParameter("MARGRECIBHORA", mARGRECIBHORA) :
                new ObjectParameter("MARGRECIBHORA", typeof(string));
    
            var mARGRECIBNOMBREParameter = mARGRECIBNOMBRE != null ?
                new ObjectParameter("MARGRECIBNOMBRE", mARGRECIBNOMBRE) :
                new ObjectParameter("MARGRECIBNOMBRE", typeof(string));
    
            var eNVIOFISICOParameter = eNVIOFISICO.HasValue ?
                new ObjectParameter("ENVIOFISICO", eNVIOFISICO) :
                new ObjectParameter("ENVIOFISICO", typeof(byte));
    
            var eNVIODIGITALParameter = eNVIODIGITAL.HasValue ?
                new ObjectParameter("ENVIODIGITAL", eNVIODIGITAL) :
                new ObjectParameter("ENVIODIGITAL", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiContSV_Result>("sp_margiContSV", mARGICONTIDParameter, mARGIDParameter, cONTIDParameter, tIPOIDParameter, mARGRECIBFECParameter, mARGRECIBHORAParameter, mARGRECIBNOMBREParameter, eNVIOFISICOParameter, eNVIODIGITALParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_marginadoDL_Result> sp_marginadoDL(Nullable<int> mARGID)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoDL_Result>("sp_marginadoDL", mARGIDParameter);
        }
    
        public virtual ObjectResult<sp_marginaRecibeUpdateSV_Result> sp_marginaRecibeUpdateSV(Nullable<int> mARGICONTID, Nullable<System.DateTime> mARGRECIBFEC, string mARGRECIBHORA, string mARGRECIBNOMBRE, Nullable<int> uPDATEUSRID)
        {
            var mARGICONTIDParameter = mARGICONTID.HasValue ?
                new ObjectParameter("MARGICONTID", mARGICONTID) :
                new ObjectParameter("MARGICONTID", typeof(int));
    
            var mARGRECIBFECParameter = mARGRECIBFEC.HasValue ?
                new ObjectParameter("MARGRECIBFEC", mARGRECIBFEC) :
                new ObjectParameter("MARGRECIBFEC", typeof(System.DateTime));
    
            var mARGRECIBHORAParameter = mARGRECIBHORA != null ?
                new ObjectParameter("MARGRECIBHORA", mARGRECIBHORA) :
                new ObjectParameter("MARGRECIBHORA", typeof(string));
    
            var mARGRECIBNOMBREParameter = mARGRECIBNOMBRE != null ?
                new ObjectParameter("MARGRECIBNOMBRE", mARGRECIBNOMBRE) :
                new ObjectParameter("MARGRECIBNOMBRE", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginaRecibeUpdateSV_Result>("sp_marginaRecibeUpdateSV", mARGICONTIDParameter, mARGRECIBFECParameter, mARGRECIBHORAParameter, mARGRECIBNOMBREParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_margiContGT_Result> sp_margiContGT(Nullable<int> mARGID)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiContGT_Result>("sp_margiContGT", mARGIDParameter);
        }
    
        public virtual ObjectResult<sp_correspondenciaSV_Result> sp_correspondenciaSV(Nullable<int> cORRESID, string cORRESCOD, Nullable<int> cLASEID, Nullable<int> tIPOID, Nullable<int> pRIOID, Nullable<int> cONTID_REMITE, Nullable<int> cATEGOID, string aSUNTO, Nullable<System.DateTime> nOTAELABFEC, Nullable<System.DateTime> nOTARECIBFEC, string nOTARECIBHORA, Nullable<byte> rEQFIRMA, Nullable<int> cONTID_DIRIGIDO, Nullable<int> cONTID_ELABORO, Nullable<int> cORRESID_CONTESTA, Nullable<int> mARGINAID, string mARGINAFORMARES, Nullable<byte> eLIMINADO, Nullable<int> uPDATEUSRID, Nullable<int> rESPONSABLEID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var cORRESCODParameter = cORRESCOD != null ?
                new ObjectParameter("CORRESCOD", cORRESCOD) :
                new ObjectParameter("CORRESCOD", typeof(string));
    
            var cLASEIDParameter = cLASEID.HasValue ?
                new ObjectParameter("CLASEID", cLASEID) :
                new ObjectParameter("CLASEID", typeof(int));
    
            var tIPOIDParameter = tIPOID.HasValue ?
                new ObjectParameter("TIPOID", tIPOID) :
                new ObjectParameter("TIPOID", typeof(int));
    
            var pRIOIDParameter = pRIOID.HasValue ?
                new ObjectParameter("PRIOID", pRIOID) :
                new ObjectParameter("PRIOID", typeof(int));
    
            var cONTID_REMITEParameter = cONTID_REMITE.HasValue ?
                new ObjectParameter("CONTID_REMITE", cONTID_REMITE) :
                new ObjectParameter("CONTID_REMITE", typeof(int));
    
            var cATEGOIDParameter = cATEGOID.HasValue ?
                new ObjectParameter("CATEGOID", cATEGOID) :
                new ObjectParameter("CATEGOID", typeof(int));
    
            var aSUNTOParameter = aSUNTO != null ?
                new ObjectParameter("ASUNTO", aSUNTO) :
                new ObjectParameter("ASUNTO", typeof(string));
    
            var nOTAELABFECParameter = nOTAELABFEC.HasValue ?
                new ObjectParameter("NOTAELABFEC", nOTAELABFEC) :
                new ObjectParameter("NOTAELABFEC", typeof(System.DateTime));
    
            var nOTARECIBFECParameter = nOTARECIBFEC.HasValue ?
                new ObjectParameter("NOTARECIBFEC", nOTARECIBFEC) :
                new ObjectParameter("NOTARECIBFEC", typeof(System.DateTime));
    
            var nOTARECIBHORAParameter = nOTARECIBHORA != null ?
                new ObjectParameter("NOTARECIBHORA", nOTARECIBHORA) :
                new ObjectParameter("NOTARECIBHORA", typeof(string));
    
            var rEQFIRMAParameter = rEQFIRMA.HasValue ?
                new ObjectParameter("REQFIRMA", rEQFIRMA) :
                new ObjectParameter("REQFIRMA", typeof(byte));
    
            var cONTID_DIRIGIDOParameter = cONTID_DIRIGIDO.HasValue ?
                new ObjectParameter("CONTID_DIRIGIDO", cONTID_DIRIGIDO) :
                new ObjectParameter("CONTID_DIRIGIDO", typeof(int));
    
            var cONTID_ELABOROParameter = cONTID_ELABORO.HasValue ?
                new ObjectParameter("CONTID_ELABORO", cONTID_ELABORO) :
                new ObjectParameter("CONTID_ELABORO", typeof(int));
    
            var cORRESID_CONTESTAParameter = cORRESID_CONTESTA.HasValue ?
                new ObjectParameter("CORRESID_CONTESTA", cORRESID_CONTESTA) :
                new ObjectParameter("CORRESID_CONTESTA", typeof(int));
    
            var mARGINAIDParameter = mARGINAID.HasValue ?
                new ObjectParameter("MARGINAID", mARGINAID) :
                new ObjectParameter("MARGINAID", typeof(int));
    
            var mARGINAFORMARESParameter = mARGINAFORMARES != null ?
                new ObjectParameter("MARGINAFORMARES", mARGINAFORMARES) :
                new ObjectParameter("MARGINAFORMARES", typeof(string));
    
            var eLIMINADOParameter = eLIMINADO.HasValue ?
                new ObjectParameter("ELIMINADO", eLIMINADO) :
                new ObjectParameter("ELIMINADO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            var rESPONSABLEIDParameter = rESPONSABLEID.HasValue ?
                new ObjectParameter("RESPONSABLEID", rESPONSABLEID) :
                new ObjectParameter("RESPONSABLEID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_correspondenciaSV_Result>("sp_correspondenciaSV", cORRESIDParameter, cORRESCODParameter, cLASEIDParameter, tIPOIDParameter, pRIOIDParameter, cONTID_REMITEParameter, cATEGOIDParameter, aSUNTOParameter, nOTAELABFECParameter, nOTARECIBFECParameter, nOTARECIBHORAParameter, rEQFIRMAParameter, cONTID_DIRIGIDOParameter, cONTID_ELABOROParameter, cORRESID_CONTESTAParameter, mARGINAIDParameter, mARGINAFORMARESParameter, eLIMINADOParameter, uPDATEUSRIDParameter, rESPONSABLEIDParameter);
        }
    
        public virtual ObjectResult<sp_margiActiveRepGT_Result> sp_margiActiveRepGT(Nullable<System.DateTime> fECHMARGI01, Nullable<System.DateTime> fECHMARGI02, Nullable<int> grupo)
        {
            var fECHMARGI01Parameter = fECHMARGI01.HasValue ?
                new ObjectParameter("FECHMARGI01", fECHMARGI01) :
                new ObjectParameter("FECHMARGI01", typeof(System.DateTime));
    
            var fECHMARGI02Parameter = fECHMARGI02.HasValue ?
                new ObjectParameter("FECHMARGI02", fECHMARGI02) :
                new ObjectParameter("FECHMARGI02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiActiveRepGT_Result>("sp_margiActiveRepGT", fECHMARGI01Parameter, fECHMARGI02Parameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_marginadoByIdGT_Result> sp_marginadoByIdGT(Nullable<int> mARGID)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoByIdGT_Result>("sp_marginadoByIdGT", mARGIDParameter);
        }
    
        public virtual ObjectResult<sp_marginadoGT_Result> sp_marginadoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoGT_Result>("sp_marginadoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_marginadoPendientesByFechaGT_Result> sp_marginadoPendientesByFechaGT(Nullable<System.DateTime> fECHMARGI01, Nullable<System.DateTime> fECHMARGI02, Nullable<int> grupo)
        {
            var fECHMARGI01Parameter = fECHMARGI01.HasValue ?
                new ObjectParameter("FECHMARGI01", fECHMARGI01) :
                new ObjectParameter("FECHMARGI01", typeof(System.DateTime));
    
            var fECHMARGI02Parameter = fECHMARGI02.HasValue ?
                new ObjectParameter("FECHMARGI02", fECHMARGI02) :
                new ObjectParameter("FECHMARGI02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoPendientesByFechaGT_Result>("sp_marginadoPendientesByFechaGT", fECHMARGI01Parameter, fECHMARGI02Parameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_marginadoSV_Result> sp_marginadoSV(Nullable<int> mARGID, Nullable<int> cORRESID, Nullable<System.DateTime> mARGFEC, Nullable<System.DateTime> mARGTIEMPO, string mARGMOTIVO, Nullable<byte> mARGPENDIENTE, Nullable<int> mARGINSTRUC, Nullable<int> uPDATEUSRID, string mARGINADOPOR)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var mARGFECParameter = mARGFEC.HasValue ?
                new ObjectParameter("MARGFEC", mARGFEC) :
                new ObjectParameter("MARGFEC", typeof(System.DateTime));
    
            var mARGTIEMPOParameter = mARGTIEMPO.HasValue ?
                new ObjectParameter("MARGTIEMPO", mARGTIEMPO) :
                new ObjectParameter("MARGTIEMPO", typeof(System.DateTime));
    
            var mARGMOTIVOParameter = mARGMOTIVO != null ?
                new ObjectParameter("MARGMOTIVO", mARGMOTIVO) :
                new ObjectParameter("MARGMOTIVO", typeof(string));
    
            var mARGPENDIENTEParameter = mARGPENDIENTE.HasValue ?
                new ObjectParameter("MARGPENDIENTE", mARGPENDIENTE) :
                new ObjectParameter("MARGPENDIENTE", typeof(byte));
    
            var mARGINSTRUCParameter = mARGINSTRUC.HasValue ?
                new ObjectParameter("MARGINSTRUC", mARGINSTRUC) :
                new ObjectParameter("MARGINSTRUC", typeof(int));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            var mARGINADOPORParameter = mARGINADOPOR != null ?
                new ObjectParameter("MARGINADOPOR", mARGINADOPOR) :
                new ObjectParameter("MARGINADOPOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoSV_Result>("sp_marginadoSV", mARGIDParameter, cORRESIDParameter, mARGFECParameter, mARGTIEMPOParameter, mARGMOTIVOParameter, mARGPENDIENTEParameter, mARGINSTRUCParameter, uPDATEUSRIDParameter, mARGINADOPORParameter);
        }
    
        public virtual ObjectResult<sp_margiRepGT_Result> sp_margiRepGT(Nullable<System.DateTime> fECHMARGI01, Nullable<System.DateTime> fECHMARGI02, Nullable<int> grupo)
        {
            var fECHMARGI01Parameter = fECHMARGI01.HasValue ?
                new ObjectParameter("FECHMARGI01", fECHMARGI01) :
                new ObjectParameter("FECHMARGI01", typeof(System.DateTime));
    
            var fECHMARGI02Parameter = fECHMARGI02.HasValue ?
                new ObjectParameter("FECHMARGI02", fECHMARGI02) :
                new ObjectParameter("FECHMARGI02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiRepGT_Result>("sp_margiRepGT", fECHMARGI01Parameter, fECHMARGI02Parameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_marginadoMarcaDL_Result> sp_marginadoMarcaDL(Nullable<int> mARGID, Nullable<int> uPDATEUSRID)
        {
            var mARGIDParameter = mARGID.HasValue ?
                new ObjectParameter("MARGID", mARGID) :
                new ObjectParameter("MARGID", typeof(int));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoMarcaDL_Result>("sp_marginadoMarcaDL", mARGIDParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_enviadoGT_Result> sp_enviadoGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoGT_Result>("sp_enviadoGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_enviadoSinResByFechaGT_Result> sp_enviadoSinResByFechaGT(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> grupo)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoSinResByFechaGT_Result>("sp_enviadoSinResByFechaGT", fECH01Parameter, fECH02Parameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_enviadoSV_Result> sp_enviadoSV(Nullable<int> eNVIAID, Nullable<int> cONTID, Nullable<int> cORRESID, Nullable<System.DateTime> eNVIOFEC, Nullable<System.DateTime> eNVIORECIBFEC, string eNVIORECIBHORA, string eNVIORECIBNOMBRE, Nullable<int> eNVIOINSTRUC, Nullable<byte> eNVIODIGITAL, Nullable<byte> eNVIOFISICO, Nullable<int> uPDATEUSRID)
        {
            var eNVIAIDParameter = eNVIAID.HasValue ?
                new ObjectParameter("ENVIAID", eNVIAID) :
                new ObjectParameter("ENVIAID", typeof(int));
    
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            var eNVIOFECParameter = eNVIOFEC.HasValue ?
                new ObjectParameter("ENVIOFEC", eNVIOFEC) :
                new ObjectParameter("ENVIOFEC", typeof(System.DateTime));
    
            var eNVIORECIBFECParameter = eNVIORECIBFEC.HasValue ?
                new ObjectParameter("ENVIORECIBFEC", eNVIORECIBFEC) :
                new ObjectParameter("ENVIORECIBFEC", typeof(System.DateTime));
    
            var eNVIORECIBHORAParameter = eNVIORECIBHORA != null ?
                new ObjectParameter("ENVIORECIBHORA", eNVIORECIBHORA) :
                new ObjectParameter("ENVIORECIBHORA", typeof(string));
    
            var eNVIORECIBNOMBREParameter = eNVIORECIBNOMBRE != null ?
                new ObjectParameter("ENVIORECIBNOMBRE", eNVIORECIBNOMBRE) :
                new ObjectParameter("ENVIORECIBNOMBRE", typeof(string));
    
            var eNVIOINSTRUCParameter = eNVIOINSTRUC.HasValue ?
                new ObjectParameter("ENVIOINSTRUC", eNVIOINSTRUC) :
                new ObjectParameter("ENVIOINSTRUC", typeof(int));
    
            var eNVIODIGITALParameter = eNVIODIGITAL.HasValue ?
                new ObjectParameter("ENVIODIGITAL", eNVIODIGITAL) :
                new ObjectParameter("ENVIODIGITAL", typeof(byte));
    
            var eNVIOFISICOParameter = eNVIOFISICO.HasValue ?
                new ObjectParameter("ENVIOFISICO", eNVIOFISICO) :
                new ObjectParameter("ENVIOFISICO", typeof(byte));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoSV_Result>("sp_enviadoSV", eNVIAIDParameter, cONTIDParameter, cORRESIDParameter, eNVIOFECParameter, eNVIORECIBFECParameter, eNVIORECIBHORAParameter, eNVIORECIBNOMBREParameter, eNVIOINSTRUCParameter, eNVIODIGITALParameter, eNVIOFISICOParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_contactosUpMailSV_Result> sp_contactosUpMailSV(Nullable<int> cONTID, string cONTEMAIL, Nullable<int> uPDATEUSRID)
        {
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var cONTEMAILParameter = cONTEMAIL != null ?
                new ObjectParameter("CONTEMAIL", cONTEMAIL) :
                new ObjectParameter("CONTEMAIL", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactosUpMailSV_Result>("sp_contactosUpMailSV", cONTIDParameter, cONTEMAILParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_enviadoRecibeUpdateSV_Result> sp_enviadoRecibeUpdateSV(Nullable<int> eNVIAID, Nullable<System.DateTime> eNVIORECIBFEC, string eNVIORECIBHORA, string eNVIORECIBNOMBRE, Nullable<int> uPDATEUSRID)
        {
            var eNVIAIDParameter = eNVIAID.HasValue ?
                new ObjectParameter("ENVIAID", eNVIAID) :
                new ObjectParameter("ENVIAID", typeof(int));
    
            var eNVIORECIBFECParameter = eNVIORECIBFEC.HasValue ?
                new ObjectParameter("ENVIORECIBFEC", eNVIORECIBFEC) :
                new ObjectParameter("ENVIORECIBFEC", typeof(System.DateTime));
    
            var eNVIORECIBHORAParameter = eNVIORECIBHORA != null ?
                new ObjectParameter("ENVIORECIBHORA", eNVIORECIBHORA) :
                new ObjectParameter("ENVIORECIBHORA", typeof(string));
    
            var eNVIORECIBNOMBREParameter = eNVIORECIBNOMBRE != null ?
                new ObjectParameter("ENVIORECIBNOMBRE", eNVIORECIBNOMBRE) :
                new ObjectParameter("ENVIORECIBNOMBRE", typeof(string));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoRecibeUpdateSV_Result>("sp_enviadoRecibeUpdateSV", eNVIAIDParameter, eNVIORECIBFECParameter, eNVIORECIBHORAParameter, eNVIORECIBNOMBREParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_enviadoMDL_Result> sp_enviadoMDL(Nullable<int> eNVIAID, Nullable<int> uPDATEUSRID)
        {
            var eNVIAIDParameter = eNVIAID.HasValue ?
                new ObjectParameter("ENVIAID", eNVIAID) :
                new ObjectParameter("ENVIAID", typeof(int));
    
            var uPDATEUSRIDParameter = uPDATEUSRID.HasValue ?
                new ObjectParameter("UPDATEUSRID", uPDATEUSRID) :
                new ObjectParameter("UPDATEUSRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoMDL_Result>("sp_enviadoMDL", eNVIAIDParameter, uPDATEUSRIDParameter);
        }
    
        public virtual ObjectResult<sp_contByNomGT_Result> sp_contByNomGT(string cONTNOMBRE)
        {
            var cONTNOMBREParameter = cONTNOMBRE != null ?
                new ObjectParameter("CONTNOMBRE", cONTNOMBRE) :
                new ObjectParameter("CONTNOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contByNomGT_Result>("sp_contByNomGT", cONTNOMBREParameter);
        }
    
        public virtual ObjectResult<sp_margiResByContestaIdGT_Result> sp_margiResByContestaIdGT(Nullable<int> cORRESID_CONTESTA)
        {
            var cORRESID_CONTESTAParameter = cORRESID_CONTESTA.HasValue ?
                new ObjectParameter("CORRESID_CONTESTA", cORRESID_CONTESTA) :
                new ObjectParameter("CORRESID_CONTESTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_margiResByContestaIdGT_Result>("sp_margiResByContestaIdGT", cORRESID_CONTESTAParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByContTIPOGT_Result> sp_detallefullByContTIPOGT(Nullable<int> tIPO, string cONT, string tEXTO, Nullable<int> grupo)
        {
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var cONTParameter = cONT != null ?
                new ObjectParameter("CONT", cONT) :
                new ObjectParameter("CONT", typeof(string));
    
            var tEXTOParameter = tEXTO != null ?
                new ObjectParameter("TEXTO", tEXTO) :
                new ObjectParameter("TEXTO", typeof(string));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByContTIPOGT_Result>("sp_detallefullByContTIPOGT", tIPOParameter, cONTParameter, tEXTOParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_corresFull2GT_Result> sp_corresFull2GT(Nullable<int> grupo)
        {
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_corresFull2GT_Result>("sp_corresFull2GT", grupoParameter);
        }
    
        public virtual ObjectResult<sp_notificacionGT_Result1> sp_notificacionGT(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_notificacionGT_Result1>("sp_notificacionGT", useridParameter);
        }
    
        public virtual int sp_notificacionUP(Nullable<int> mensajeid, Nullable<int> userid)
        {
            var mensajeidParameter = mensajeid.HasValue ?
                new ObjectParameter("mensajeid", mensajeid) :
                new ObjectParameter("mensajeid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_notificacionUP", mensajeidParameter, useridParameter);
        }
    
        public virtual ObjectResult<sp_adjuntoDL_Result2> sp_adjuntoDL(string aDJUNTO_NAME, Nullable<int> usrs_id, Nullable<int> corresId)
        {
            var aDJUNTO_NAMEParameter = aDJUNTO_NAME != null ?
                new ObjectParameter("ADJUNTO_NAME", aDJUNTO_NAME) :
                new ObjectParameter("ADJUNTO_NAME", typeof(string));
    
            var usrs_idParameter = usrs_id.HasValue ?
                new ObjectParameter("usrs_id", usrs_id) :
                new ObjectParameter("usrs_id", typeof(int));
    
            var corresIdParameter = corresId.HasValue ?
                new ObjectParameter("CorresId", corresId) :
                new ObjectParameter("CorresId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_adjuntoDL_Result2>("sp_adjuntoDL", aDJUNTO_NAMEParameter, usrs_idParameter, corresIdParameter);
        }
    
        public virtual ObjectResult<sp_archivosGT_Result> sp_archivosGT(Nullable<int> cORRESID)
        {
            var cORRESIDParameter = cORRESID.HasValue ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_archivosGT_Result>("sp_archivosGT", cORRESIDParameter);
        }
    
        public virtual ObjectResult<sp_contactoDL_Result> sp_contactoDL(Nullable<int> contactoid, Nullable<int> usuarioid)
        {
            var contactoidParameter = contactoid.HasValue ?
                new ObjectParameter("contactoid", contactoid) :
                new ObjectParameter("contactoid", typeof(int));
    
            var usuarioidParameter = usuarioid.HasValue ?
                new ObjectParameter("usuarioid", usuarioid) :
                new ObjectParameter("usuarioid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_contactoDL_Result>("sp_contactoDL", contactoidParameter, usuarioidParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByFechaContIDGT_Result> sp_detallefullByFechaContIDGT(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> cONTID, Nullable<int> grupo)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByFechaContIDGT_Result>("sp_detallefullByFechaContIDGT", fECH01Parameter, fECH02Parameter, cONTIDParameter, grupoParameter);
        }
    
        public virtual ObjectResult<sp_enviadoSinResByFechaGTV2_Result> sp_enviadoSinResByFechaGTV2(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> grupo, Nullable<int> tipoC)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var tipoCParameter = tipoC.HasValue ?
                new ObjectParameter("TipoC", tipoC) :
                new ObjectParameter("TipoC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_enviadoSinResByFechaGTV2_Result>("sp_enviadoSinResByFechaGTV2", fECH01Parameter, fECH02Parameter, grupoParameter, tipoCParameter);
        }
    
        public virtual ObjectResult<sp_marginadoPendientesByFechaGTV2_Result> sp_marginadoPendientesByFechaGTV2(Nullable<System.DateTime> fECHMARGI01, Nullable<System.DateTime> fECHMARGI02, Nullable<int> grupo, Nullable<int> tipoC)
        {
            var fECHMARGI01Parameter = fECHMARGI01.HasValue ?
                new ObjectParameter("FECHMARGI01", fECHMARGI01) :
                new ObjectParameter("FECHMARGI01", typeof(System.DateTime));
    
            var fECHMARGI02Parameter = fECHMARGI02.HasValue ?
                new ObjectParameter("FECHMARGI02", fECHMARGI02) :
                new ObjectParameter("FECHMARGI02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var tipoCParameter = tipoC.HasValue ?
                new ObjectParameter("TipoC", tipoC) :
                new ObjectParameter("TipoC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_marginadoPendientesByFechaGTV2_Result>("sp_marginadoPendientesByFechaGTV2", fECHMARGI01Parameter, fECHMARGI02Parameter, grupoParameter, tipoCParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByFechaGTV2_Result> sp_detallefullByFechaGTV2(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> grupo, Nullable<int> tipoC)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var tipoCParameter = tipoC.HasValue ?
                new ObjectParameter("TipoC", tipoC) :
                new ObjectParameter("TipoC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByFechaGTV2_Result>("sp_detallefullByFechaGTV2", fECH01Parameter, fECH02Parameter, grupoParameter, tipoCParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByFechaContIDGTV2_Result> sp_detallefullByFechaContIDGTV2(Nullable<System.DateTime> fECH01, Nullable<System.DateTime> fECH02, Nullable<int> cONTID, Nullable<int> grupo, Nullable<int> tipoC)
        {
            var fECH01Parameter = fECH01.HasValue ?
                new ObjectParameter("FECH01", fECH01) :
                new ObjectParameter("FECH01", typeof(System.DateTime));
    
            var fECH02Parameter = fECH02.HasValue ?
                new ObjectParameter("FECH02", fECH02) :
                new ObjectParameter("FECH02", typeof(System.DateTime));
    
            var cONTIDParameter = cONTID.HasValue ?
                new ObjectParameter("CONTID", cONTID) :
                new ObjectParameter("CONTID", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var tipoCParameter = tipoC.HasValue ?
                new ObjectParameter("TipoC", tipoC) :
                new ObjectParameter("TipoC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByFechaContIDGTV2_Result>("sp_detallefullByFechaContIDGTV2", fECH01Parameter, fECH02Parameter, cONTIDParameter, grupoParameter, tipoCParameter);
        }
    
        public virtual ObjectResult<sp_detallefullByIdsGT_Result> sp_detallefullByIdsGT(string cORRESID, Nullable<int> grupo)
        {
            var cORRESIDParameter = cORRESID != null ?
                new ObjectParameter("CORRESID", cORRESID) :
                new ObjectParameter("CORRESID", typeof(string));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detallefullByIdsGT_Result>("sp_detallefullByIdsGT", cORRESIDParameter, grupoParameter);
        }
    }
}
